STOCK MARKET

In [2]:
pip install pandas 

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.0 -> 25.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.0 -> 25.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [4]:

import numpy as np
import pandas as pd

In [5]:
df=pd.read_csv("stock_data.csv")

In [6]:
df.head()

,Text,Sentiment
0,Kickers on my watchlist XIDE TIT SOQ PNK CPW B...,1
1,user: AAP MOVIE. 55% return for the FEA/GEED i...,1
2,user I'd be afraid to short AMZN - they are lo...,1
3,MNTA Over 12.00,1
4,OI Over 21.37,1


In [7]:
df.tail()

,Text,Sentiment
5786,Industry body CII said #discoms are likely to ...,-1
5787,"#Gold prices slip below Rs 46,000 as #investor...",-1
5788,Workers at Bajaj Auto have agreed to a 10% wag...,1
5789,"#Sharemarket LIVE: Sensex off day’s high, up 6...",1
5790,"#Sensex, #Nifty climb off day's highs, still u...",1


In [8]:
df.isnull().sum()

Text         0
Sentiment    0
dtype: int64

In [9]:
df['Text']

0       Kickers on my watchlist XIDE TIT SOQ PNK CPW B...
1       user: AAP MOVIE. 55% return for the FEA/GEED i...
2       user I'd be afraid to short AMZN - they are lo...
3                                       MNTA Over 12.00  
4                                        OI  Over 21.37  
                              ...                        
5786    Industry body CII said #discoms are likely to ...
5787    #Gold prices slip below Rs 46,000 as #investor...
5788    Workers at Bajaj Auto have agreed to a 10% wag...
5789    #Sharemarket LIVE: Sensex off day’s high, up 6...
5790    #Sensex, #Nifty climb off day's highs, still u...
Name: Text, Length: 5791, dtype: object

In [10]:
import re  # Regular expressions for text cleaning

cleaned = []  # List to store cleaned text
for text in df['Text']:  # Looping through each message in the 'Message' column
    cleaned_text = re.sub(r'[^\w\s]', '', text)  # Removing all characters except words and spaces
    cleaned_text = re.sub(r'\s+', ' ', cleaned_text)  # Replacing multiple spaces with a single space
    cleaned_data = cleaned_text.strip()  # Stripping leading and trailing whitespace
    cleaned.append(cleaned_data)

In [11]:
cleaned[0]

'Kickers on my watchlist XIDE TIT SOQ PNK CPW BPZ AJ trade method 1 or method 2 see prev posts'

In [12]:
pip install nltk

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.0 -> 25.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [13]:
import nltk
from nltk.tokenize import word_tokenize,sent_tokenize
from nltk.corpus import stopwords
nltk.download('punkt')
nltk.download('punkt_tab')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Lenovo\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\Lenovo\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Lenovo\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [14]:
tokens = [word_tokenize(x) for x in cleaned]
stop = set(stopwords.words('english'))
stop_token = []
for k in range(len(df['Text'])):
    p = [i for i in tokens[k] if i not in stop]
    stop_token.append(p)

In [15]:
from nltk.stem import PorterStemmer
ps=PorterStemmer()

In [16]:
stemmeddata=[]
for message in stop_token:
   st=[ps.stem(word) for word in message]
   stemmeddata.append(st)

In [17]:
from nltk.tag import pos_tag
nltk.download('averaged_perceptron_tagger_eng')

[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     C:\Users\Lenovo\AppData\Roaming\nltk_data...
[nltk_data]   Package averaged_perceptron_tagger_eng is already up-to-
[nltk_data]       date!


True

In [18]:
pos_token=[pos_tag(text) for text in stop_token]

In [19]:
pos_token[0]

[('Kickers', 'NNS'),
 ('watchlist', 'VBP'),
 ('XIDE', 'NNP'),
 ('TIT', 'NNP'),
 ('SOQ', 'NNP'),
 ('PNK', 'NNP'),
 ('CPW', 'NNP'),
 ('BPZ', 'NNP'),
 ('AJ', 'NNP'),
 ('trade', 'NN'),
 ('method', 'NN'),
 ('1', 'CD'),
 ('method', 'NN'),
 ('2', 'CD'),
 ('see', 'NN'),
 ('prev', 'JJ'),
 ('posts', 'NNS')]

In [20]:
stemmeddata[0]

['kicker',
 'watchlist',
 'xide',
 'tit',
 'soq',
 'pnk',
 'cpw',
 'bpz',
 'aj',
 'trade',
 'method',
 '1',
 'method',
 '2',
 'see',
 'prev',
 'post']

In [21]:
stem_vector=[''.join(text) for text in stemmeddata]

In [22]:
stem_vector[0]

'kickerwatchlistxidetitsoqpnkcpwbpzajtrademethod1method2seeprevpost'

In [23]:
pip install scikit-learn


Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.0 -> 25.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [24]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer()

In [25]:
X=cv.fit_transform(stem_vector).toarray()

In [26]:
y=df['Sentiment']

In [27]:
from sklearn.naive_bayes import MultinomialNB
mb=MultinomialNB()
mb.fit(X,y)

MultinomialNB()

In [28]:
mb.predict([X[2]])

array([1])

In [29]:
mb.predict(X)

array([1, 1, 1, ..., 1, 1, 1], shape=(5791,))

In [30]:
[mb.predict([X[i]]) for i in range(len(X))]

[array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([-1]),
 array([-1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([-1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([-1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([-1]),
 array([1]),
 array([1]),
 array([-1]),
 array([1]),
 array([1]),
 array([1]),
 array([-1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([-1]),
 array([1]),
 array([-1]),
 array([1]),
 array([1]),
 array([1]),
 array([-1]),
 array([-1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 

In [31]:
label_map={1:'positive',-1:"negative"}

In [32]:
z=mb.predict(X)
pd.Series(z).value_counts()

 1    3685
-1    2106
Name: count, dtype: int64

In [33]:
for row in X:
    predicted_num=mb.predict([row])[0]
    predicted_label=label_map[predicted_num]
    print(predicted_label)

positive
positive
positive
positive
positive
positive
negative
negative
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
negative
positive
positive
positive
positive
negative
positive
positive
positive
positive
negative
positive
positive
negative
positive
positive
positive
negative
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
negative
positive
negative
positive
positive
positive
negative
negative
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
positive
negative
positive
positive
positive
positive
positive
positive
positive
positive
positive
negative
positive
positive
positive
positive
negative
positive
negative
positive
positive
negative
positive
negative
positive
p

In [34]:
mb.score(X,y)

1.0

In [35]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


In [36]:
# Train the model
mb.fit(X_train, y_train)

# Predict on test set
y_pred = mb.predict(X_test)

# Evaluate model accuracy
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test, y_pred)
print("Test Accuracy:", accuracy)


Test Accuracy: 0.635030198446937


In [38]:
new_texts = ["This stock is performing great!", "bad investment."]
new_texts_cleaned = [" ".join([ps.stem(word) for word in word_tokenize(re.sub(r'[^\\w\\s]', '', text)) if word.lower() not in stop]) for text in new_texts]
new_X = cv.transform(new_texts_cleaned).toarray()

predictions = mb.predict(new_X)
print("Predictions:", predictions)


Predictions: [1 1]


In [39]:
df.shape

(5791, 2)

In [40]:
import pickle

with open("sentiment_model.pkl", "wb") as f:
    pickle.dump(mb, f)


In [41]:
with open("sentiment_model.pkl", "rb") as f:
    loaded_model = pickle.load(f)

# Use the loaded model for predictions
y_new_pred = loaded_model.predict(new_X)
print("Predictions:", y_new_pred)

Predictions: [1 1]
